### ISSUE TITLE
Exported dxfs cause AutoCAD to hang

### ISSUE THREAD

**Issue by diffendale** [totalopenstation/totalopenstation#66] opened 2016-07-05 23:11 UTC
Last summer I ran TOPS (Win 7 x64) to transfer data from a Leica TCR 407power, followed by exporting to dxf and opening in AutoCAD 2016. No problems.

This summer, same computer, same installation of TOPS (though I have just now tried the new portable version, with the same results), same installation of AutoCAD, downloading from a different Leica TS, a TCR 805. When I attempt to open the exported dxfs in AutoCAD, the program hangs. Sometimes it stops hanging after a few minutes, but there is no sign of the file I was attempting to open; other times, it seems to hang indefinitely (though maybe these are just the times I'm less patient). I can see that the data have been successfully transferred to from the TS to TOPS, but I cannot directly access them in AutoCAD via the exported dxf (of course there are workarounds to get the data into CAD, but I would prefer to be able to open the dxf directly...).

**Comment by steko** [comment] 2016-07-06 05:12
Thanks for reporting your problem, Dan. If you could attach the incriminated files to this issue (both the DXF and the data that you downloaded from the TCR 805), I'm sure we can find what is wrong with TOPS.

If the files are not allowed by GitHub a zip  should work.

Il 06 luglio 2016 01:11:49 CEST, Dan Diffendale notifications@github.com ha scritto:

**Comment by diffendale** [comment] 2016-07-06 17:21
Here they are!

[TOPS_data.zip](https://github.com/steko/totalopenstation/files/350464/TOPS_data.zip)

**Comment by steko** [comment] 2016-07-06 18:37
Thank you! I started looking at the files :mag_right: 

First, the DXF: it opens correctly in both QGIS and QCAD for me, but that is not very surprising since those are the two apps that I routinely use and that I used for testing DXF created by TOPS.

Here is a screenshot, perhaps you can recognize familiar feature shapes? Just to confirm if the problem is to be found in the way we structure the DXF output, not in the data processing step.

![2016-07-05](https://cloud.githubusercontent.com/assets/40545/16629053/9cddb248-43b4-11e6-9534-0c96ecb588de.png)

The raw data is standard GSI16 with fields 21, 22, 31, 81, 82, 83, 87. I'm sure @psolyca can shed some light since he's been improving support for GSI (that is still not included in the current version).

**Comment by diffendale** [comment] 2016-07-06 21:15
Thanks! Yes, that's the right data, all in the right place.

**Comment by psolyca** [comment] 2016-07-07 08:59
So I try with 3 differents softwares :
- DraftSight
- DWG TrueView
- de-caff Viewer

As a result the 2 last were not able to open the DXFf but I had an error message. DraftSight was able to open the file but with differents messages.

So two bugs in one.

First, the header of the DXF was not complete
Second, the color index must be in the range of 256

This should be fix in commit adcfa099838d214ecc38e7a413c62dd66ace1808.

Oops as usual, I forgot the unittest. Fix on commit e68f76749d269afe914037229d6a472c7d30f093

**Comment by steko** [comment] 2016-07-07 10:55
> Oops as usual, I forgot the unittest. Fix on commit e68f767

Don't worry! It would have been even easier to extend the unit test with the required parts of the DXF as a first step (e.g. describe the desired output) and then fix the bug in the code. :necktie:

**Comment by steko** [comment] 2016-07-30 07:06
@diffendale did you have a chance to test the updated version with the fixes by @psolyca ? I could upload a new version of the portable app if needed.

**Comment by steko** [comment] 2016-09-19 18:56
If there is no further input on this, I will close this issue since all testing made after the fix provided by @psolyca has returned positive results.

**Comment by psolyca** [comment] 2016-09-19 19:02
I was also thinking of closing this issue.

**Comment by diffendale** [comment] 2016-09-19 20:16
Sorry, I was in the middle of leaving Rome and heading to a wedding on July 30 and overlooked this. If you upload a new version of the portable, I'll give it a try with my data.

**Closed as completed** 2017-02-20 15:04 UTC
Labels: bug, data export
